### ISSUE TITLE
No Docker Image

### ISSUE THREAD

**Issue by Kristopherlb** [evernote/serge-dockerfiles#1]
Looks like the image on Docker Hub the docs reference is gone.

https://hub.docker.com/r/afan/serge/

**Comment by joeblew99** [comment]
yep

**Comment by iafan** [comment]
The image that is gone was built off an old Dockerfile; right now Serge is moving towards a new approach with the new Dockerfile that is a part of the main repo: https://github.com/evernote/serge/blob/master/docker/Dockerfile

This separate repository will likely be formally deprecated soon.
